[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "9c206c07908ba5999d812bf68386a506187b2382"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "d425423d8acd2d7231e34ed78463695961140669f1070d57bfef1b438f390741"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.aarch64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "02caa9ccc73ac1cc2790932a454225eaa1567363"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "5e77d4f62b8b547d594fe4eda0b25db304376bb174314649f2a774a44fa0a2c1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.aarch64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "d6dd930acad66515c5ac301048d31ea922cf66c0"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "82e26e72e5c76cf27e8f4e71d96bdf1b29857665ab90283e8492d84dace40778"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a26f79bcd2a9008273ed66370caf4d24d910f2fe"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "ae06d7baab6645ad9cc1c4a36b470279bf4a0b5cef7c5a9d8b1628e593ac04a3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d155e875e50cc9d99661e8224b29d279e56a110e"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "23307865ad810bb033bbc976f2ad908fb2b4e98c6fdbac06dee94515ea74bdca"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b30af2bd83eda9d218aa9d696fc704ce6a30178"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "2d370706cfb9b26b641618cff08c48cdb476140ca172d6bfdacb24a9c711d0ed"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d0e2c6e30a5f77ef2ae4a599431b41c2c568f41"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "c0eb8a07352610d96a12cf23e862305e359bd7bac0a34aa16a4e03caf488432f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "55cbd9e694f870c774785e1106a75d8d4181b0ef"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "5603f2c08eb098089e8e4085dfae8ab98cfb9f4e5a2e71092938c32a7c39b7e6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.i686-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "bef3974baf0a29c2fdeb18ab435492119a7d3608"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "9773db1e0df26b99bad8f3915b3937e92d64063278ac7b41aa99378beb0f0c77"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.i686-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "powerpc64le"
git-tree-sha1 = "e7795916b87a681200a2d90fe1074ca4dd2349f1"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "0acd06f19d84c4658b76f2d3c5d03fc2f83bc4228c1c4a4e995e338952d04783"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "5eb40bbada109bbea38f58b9e77a72a4900a0d63"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "797cb5ea031e5797b6186eaebe386962f8e67a480e9b09df6a7412025316e133"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.x86_64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "e5e91b18b2735172d67addef0e395b9f8e8d47e8"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "b83717c84d99bc67cbb4f0e9b30487fd527dd0d971af0baa8191ecf41572274b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.x86_64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "4954a0988601be4340d1dc2383ca92e1c6302d71"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "4e6a090ec6383ea5ffad409dc5a82682470f043b182326493da5dead4cd286d5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.6+1/Xorg_xkbcomp.v1.4.6.x86_64-unknown-freebsd.tar.gz"
