[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "c0cb008e6839f8f5faba784bebc0c55af6e800ea"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "f2249ae04d9ef532feaf726b00393caa21ad04c9c80b4ec1d11c95e906fd6087"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.aarch64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "50e6849dbc46905a4c906a70d72dc91a69762429"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "ff7605ce9b5996da402dfc750a6fbd8422d65eef0161bc7d08ca671707058c41"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.aarch64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "19d5488c6f7f788f8cd654d9d86b053eacebfe72"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "b80d42924939d96640b7a2b3519a2dc72db9fdb18fe421b10cae3f37d5da12ec"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bfea33c3efb8a29a30344b444f6c3467e89576ec"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "67499a681719c611b03e5e918f4c2262eda6bc1ac85c43686829c333bf7b69a7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7123462f7c6d3944573dccb138693e859daeb105"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "0b5427e4b5beb5068470af6f966c2f54a0e4b53d32333314bbcde59b1beede20"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebfdce55cc97700594a6c2392f5a4f03de5fd4b4"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "106cd0e0a3c17a2503489eb7ffa0226a2fe81ddfcc4d4df91e6dcf11014f76d9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ee787445e81bb4811bb800d6720ddac3502a406"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "334da7ad341bcdcef556b68b6fd9e81ba2e1beba49a609bbb19e46d59242e557"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "81c908fbb54169c4564486e4d6108097b79a0bf3"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "d6032c1c35493ce1f207a5d7014abd1900417a0087cf9e1d3e82edb2078c16b0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.i686-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "cb413fcb8458ee145d0bd88c25571b1d545de486"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "d5a1a6db646930af440969c0eabe8032de86fcdb8c763b0aa73a0adb19275783"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.i686-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "powerpc64le"
git-tree-sha1 = "80a335ee12c99d71ebf205ad8858259c328ba500"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "902c654752cbc07bc1e524fff0dba4d9e51512fa0d9cf9af82b7fa1fb845bfd7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "riscv64"
git-tree-sha1 = "e3879d9e46183b46e7484dbade1ac4a9012817ff"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "1b1ecc5d5248c86f19e32b514772a6afbf6ce0af44c9b979c9b7dec69b772a28"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.riscv64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "713bb02c7e3bd326bc08b42dd66299c115254d6e"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "01b55a7f5c27847e5c64ef3f7c345c7d76f66e959217d682e2c3faed34fa8321"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.x86_64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "bcb7b529af4fb95602fb73cfd085e1ad39b70140"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "e08c2e82b65ccf6d218f2bf32ccb008b55e7bb4e8f78d8939c94f35e8916eabb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.x86_64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "59d2c2749e68c96caf669048bd3c9551b54e1059"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "e3f9828150def5448c2e4094dc553c6006648fd329199114a629833cce86f666"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.7+0/Xorg_xkbcomp.v1.4.7.x86_64-unknown-freebsd.tar.gz"
