[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "66441ee5874c46f76ad5f08b5a7d14c55677be56"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "6ea8da919a8e84f423388e20f265f0e529265d142999d29728fb7dc167cb09b2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.aarch64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "43d52c1461e7f570c17247983217fab0b351d99c"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "b3313f28f991071e339837e6e118276f82baf61280a38ce34e8167e9060e9f05"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.aarch64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "baeed276b73f7b9a5de52901b2d91c0e5c722e64"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "7d1b430169a6602cf380b44ac1fbab1da737603b6d9ae63917e74e4e2a3550b7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.x86_64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "powerpc64le"
git-tree-sha1 = "6b4baee1005041bd74a22be03fd848fafd754c31"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "bd252a28be6cded5aaf146c5180ac2a45e435cd72ba40e0ac690cbb1dfabf41c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "81e66e94ad15c49139a26e2cf7ff9734fe6bdec3"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "c613fc46a420550404b6418e93c265d6966ec26d000d0486427b0f0b9033da1d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "136609023bc1c7d507df2c6f839ecb70ee17d5a7"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "2273017093fbea53bc040aa1c5eade1509ab49571d5bde343459f103388d2ef2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.i686-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "269845a85e80c44078343b9b9c88eb454faf41b1"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "6e252d16254d92d1f0763d275f683c642780a9b8d13d46ecfdaf50de68b1aaff"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.i686-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "aa239220a3ae4ccbffb04f8331582561f845d207"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "d884cd7d3eaae5bbb179e83d42d7b6ea1bf02b5c679417bdb810e9d9553afe5d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "088d4ef1a8f1baef0e171badf8a7b6c6452dee94"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "80d8caacf7e9191057db79e763e98b27d3ba72e7038f1c9bc230dc603fd973c5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.x86_64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "cd12c2363dafb4587826bdca400d4a4e4e98d0c6"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "4655385ed26e18f87c20eb3ae97bcdc7ebe900cbdaa7bf74138ffab4804fcd37"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+1/Xorg_xkbcomp.v1.4.2.armv7l-linux-musleabihf.tar.gz"
