[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "1e7127d2070a743da0fa80a12229f324fac2a11f"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "4fe6618aa333e26613a3fe18fd1133f5c1dc44654d521cdc79f3da3ee262e1ef"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "5b3c300b45e5522453a977bb6c0b868df6ea9c56"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "6f50d35a2f1046d8d4d70ca57e6ab0339d1a9ca242d1bc4de25b41791ecaae2f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.i686-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "f5f78eace6c0fc8b7f5a0a19c5c3357b6e58d29f"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "e71dd3f95e32f8e7e5832cbd1988d841cf84bc1cd134d069b4abaf77c283b273"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.aarch64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "5318dde0904523337433b9a93481e064648dc6f3"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "c323ec90289a72ccc079e8e20df47a796fc33099108c2b2a8ae38cf9e24d6c65"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "9b0458859833e7f21807f95a6bf3e12b2a94ef1a"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "5f45b8a71fbcdce382d0792c141d29278f04322149c655b4c6735f45c1695bf1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.aarch64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "2665dcd527190a7ab355a949fbf82dca865c012a"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "737c0ea1af60d53b0ac7c047c278d4447d64bdfed8171b6d200498d05ed6f393"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "98b7f67c7c8130572dcc9b59b8008c545a9b2000"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "b02f73729670f5061869680e869aa9babd2a2a9208b62e6787f727e115404e66"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.i686-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "dfc9821aafceba56410845954aa3bcd17493af2c"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "ba19d8b2ea089142390a215791d171936e7d494617b5220f48becf75bebf789f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.x86_64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "65a34889f38578a8d477bdfa38c3338f163bebf9"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "15365472bb2a50157308fe03a5400ace2d8e7b9335fbfe322181719159ee7ecb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.x86_64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "powerpc64le"
git-tree-sha1 = "eb188dff823da44dc0d93d68eb858ecdb69571de"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "468639631e5ab6bc3945933c577315a7f8fe8e8ad0b7ae33d7dad7f814b9ebdb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+2/Xorg_xkbcomp.v1.4.2.powerpc64le-linux-gnu.tar.gz"
